export const projectCategories = [
    'Web Development & Design',
    'Mobile App Development',
    'Graphic Design & Multimedia',
    'Writing & Translation',
    'Digital Marketing',
    'Video & Animation',
    'Music & Audio Production',
    'Business Consulting',
    'Legal Services',
    'Accounting & Finance',
    'Engineering & Architecture',
    'Data Science & Analytics',
    'Virtual Assistance',
    'Sales & Marketing',
    'Customer Support & Service',
    'Social Media Management',
    'E-commerce Development',
    'Game Development',
    'Content Creation & Editing',
    'Research & Analysis',
]